// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjxrlcbsyrzwxudohvig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqeHJsY2JzeXJ6d3h1ZG9odmlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDUwMzMsImV4cCI6MjA2MTY4MTAzM30.OWAsFPWsLTpXmw1ILxGfSR06WqM7Vx7CXH8pHyuHvvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);